In [1]:
%matplotlib notebook
import pandas as pd
import numpy as np
import matplotlib as plt
import gmaps

In [12]:
file = 'listings.csv'
df = pd.read_csv(file)
df1 = df.loc[df['number_of_reviews']>1]
df1.describe()

,id,scrape_id,thumbnail_url,medium_url,xl_picture_url,host_id,host_acceptance_rate,host_listings_count,host_total_listings_count,neighbourhood_group_cleansed,...,number_of_reviews,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,reviews_per_month
count,4.084000e+03,4.084000e+03,0.0,0.0,0.0,4.084000e+03,0.0,4084.000000,4084.000000,0.0,...,4084.000000,4081.000000,4081.000000,4081.000000,4081.000000,4081.000000,4081.000000,4081.000000,4084.000000,4083.000000
mean,1.682354e+07,2.018083e+13,NaN,NaN,NaN,5.661148e+07,NaN,14.903526,14.903526,NaN,...,44.962537,96.720412,9.848812,9.755207,9.916197,9.908846,9.776035,9.732173,2.786239,2.922143
std,7.234798e+06,2.250276e+00,NaN,NaN,NaN,5.542752e+07,NaN,114.647710,114.647710,NaN,...,60.858772,4.390386,0.451500,0.540164,0.348435,0.364507,0.468439,0.527728,5.894043,2.479417
min,3.600000e+02,2.018083e+13,NaN,NaN,NaN,6.660000e+02,NaN,0.000000,0.000000,NaN,...,2.000000,47.000000,4.000000,5.000000,5.000000,5.000000,6.000000,5.000000,1.000000,0.030000
25%,1.235080e+07,2.018083e+13,NaN,NaN,NaN,1.171456e+07,NaN,1.000000,1.000000,NaN,...,8.000000,95.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,1.000000,0.900000
50%,1.854136e+07,2.018083e+13,NaN,NaN,NaN,3.622797e+07,NaN,1.000000,1.000000,NaN,...,22.000000,98.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,1.000000,2.320000
75%,2.251359e+07,2.018083e+13,NaN,NaN,NaN,8.755579e+07,NaN,2.000000,2.000000,NaN,...,57.000000,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,2.000000,4.300000
max,2.780639e+07,2.018083e+13,NaN,NaN,NaN,2.093911e+08,NaN,1135.000000,1135.000000,NaN,...,678.000000,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,45.000000,17.770000

In [23]:

df.dtypes

id                                    int64
listing_url                          object
scrape_id                             int64
last_scraped                         object
name                                 object
summary                              object
space                                object
description                          object
experiences_offered                  object
neighborhood_overview                object
notes                                object
transit                              object
access                               object
interaction                          object
house_rules                          object
thumbnail_url                       float64
medium_url                          float64
picture_url                          object
xl_picture_url                      float64
host_id                               int64
host_url                             object
host_name                            object
host_since                           object
host_location                        object
host_about                           object
host_response_time                   object
host_response_rate                   object
host_acceptance_rate                float64
host_is_superhost                    object
host_thumbnail_url                   object
                                     ...
extra_people                         object
minimum_nights                        int64
maximum_nights                        int64
calendar_updated                     object
has_availability                     object
availability_30                       int64
availability_60                       int64
availability_90                       int64
availability_365                      int64
calendar_last_scraped                object
number_of_reviews                     int64
first_review                         object
last_review                          object
review_scores_rating                float64
review_scores_accuracy              float64
review_scores_cleanliness           float64
review_scores_checkin               float64
review_scores_communication         float64
review_scores_location              float64
review_scores_value                 float64
requires_license                     object
license                              object
jurisdiction_names                   object
instant_bookable                     object
is_business_travel_ready             object
cancellation_policy                  object
require_guest_profile_picture        object
require_guest_phone_verification     object
calculated_host_listings_count        int64
reviews_per_month                   float64
Length: 96, dtype: object

In [29]:
df_group = df.groupby('neighbourhood_cleansed')
df_group['id'].count().sort_values(ascending = False)

neighbourhood_cleansed
Five Points                     459
Highland                        336
Capitol Hill                    278
Speer                           172
Sunnyside                       157
CBD                             154
West Highland                   148
Union Station                   142
Whittier                        132
Lincoln Park                    125
Baker                           124
West Colfax                     120
Berkeley                        120
City Park West                  120
Congress Park                   115
Sloan Lake                      115
Stapleton                       107
Jefferson Park                  104
Cheesman Park                    97
Gateway - Green Valley Ranch     97
North Capitol Hill               80
Cole                             78
Washington Park West             77
Platt Park                       74
Clayton                          73
North Park Hill                  65
Northeast Park Hill              52
University                       50
Virginia Village                 49
Hale                             48
                               ...
Overland                         28
East Colfax                      26
Cory - Merrill                   25
Montbello                        24
Windsor                          24
Mar Lee                          23
Rosedale                         23
Barnum West                      22
Ruby Hill                        22
Lowry Field                      20
Indian Creek                     19
Westwood                         16
Country Club                     16
Marston                          16
Belcaro                          16
Southmoor Park                   15
Globeville                       14
Goldsmith                        13
Harvey Park                      12
Valverde                         11
College View - South Platte      10
Fort Logan                       10
Harvey Park South                 9
Wellshire                         6
Bear Valley                       6
Auraria                           6
Sun Valley                        3
DIA                               3
Kennedy                           2
Elyria Swansea                    2
Name: id, Length: 78, dtype: int64

In [30]:
coordinates = df[['latitude','longitude']]

In [33]:
# Assign the marker layer to a variable
markers = gmaps.marker_layer(coordinates)
# Add the layer to the map
fig.add_layer(markers)
fig

NameError: name 'fig' is not defined